[features]
seeds = false
skip-lint = false

[registry]
url = "https://api.apr.dev"

[programs.localnet]
hapi_core_solana = "FgE5ySSi6fbnfYGGRyaeW8y6p8A5KybXPyQ2DdxPCNRk"

[programs.devnet]
hapi_core_solana = "hapinwqwa5qRQ3Lqzy1zELDjXV9SkeNjiyBe9dwhk5W"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run jest --verbose"
